### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Aleksuo** [Walther/minesweeper#1]
Projekti ladattu 7.4 klo. 20:30.
- Peli toimi jo kuten miinaharavan kuuluukin, tosin lippuja ei ilmeisesti voinut vielä merkata.
- Koodissa hyvä yhtenäinen koodaustyyli(kaikki nimetty selkeästi ja johdonmukaisesti).
- Luokkien metodeilla vaikutti olevan selkeästi vain yksi vastuu ja ne olivat hyvän pituisia.
- Kommentit olivat hyviä etenkin monimutkaisemmissa kohdissa.
- Luokkia kannattanee jakaa pakkauksiin selkeyden vuoksi.
- GUI ja Board luokkia voisi jakaa useampaan luokkaan:
  - GUI-luokasta  mineListenerin voisi toteuttaa omaan luokkaansa
  - Board-luokassa olevan pelilogiikan voisi eriyttää erillisiin luokkiin, jotta Board-luokan vastuulle.
    jäisi ainoastaan pelilaudan datan säilyttäminen.

Kaiken kaikkiaan projekti vaikutti olevan oikein hyvällä mallilla. Onnea jatkokehitykseen!
t:Aleksi

**Comment by Walther** [comment]
- Luokkia jaettu pakkauksiin b8b21ec
- Boardille lisätty testejä 7238e54

Ja paljon muita muutoksia. Jätän tämän issuen vielä auki, koska esim. mineListener:in erottaminen ja pelilogiikan eriyttäminen kesken.

**Comment by Walther** [comment]
- mineListener refaktoroitu erilleen a8d4c50
- Game refaktoroitu erilleen Board:ista a8d4c50

Suljetaan tiketti suoritettuna.
